# Embeddings
https://platform.openai.com/docs/models#embeddings

임베딩(Embeddings)은 텍스트를 수치적으로 표현한 값으로, 두 텍스트 간의 연관성을 측정하는 데 사용된다.

임베딩은 검색, 군집화(clustering), 추천 시스템, 이상 탐지, 분류와 같은 작업에 유용하다.

**모델 및 출력 차원**

| 모델 이름                     | 설명                                                              | 출력 차원 |
|-------------------------------|-------------------------------------------------------------------|-----------|
| **text-embedding-3-large**   | 영어 및 비영어 작업 모두에서 가장 강력한 성능을 가진 모델           | 3,072     |
| **text-embedding-3-small**   | 2세대 ada 임베딩 모델보다 성능이 향상된 모델                        | 1,536     |
| **text-embedding-ada-002**   | 1세대 모델 16개를 대체하는 가장 강력한 2세대 임베딩 모델             | 1,536     |


## MTEB Leaderboard
**Massive Text Embedding Benchmark (MTEB) Leaderboard**

https://huggingface.co/spaces/mteb/leaderboard

**MTEB Leaderboard**는 Hugging Face에서 제공하는 벤치마크 리더보드 페이지로, 다양한 언어 모델(Language Model)과 임베딩 모델(Embedding Model)의 성능을 객관적으로 비교·평가하는 공간이다.

**MTEB Leaderboard에서 순위 산정 방식**

**MTEB Leaderboard**의 순위는 다양한 자연어 처리 태스크(분류, 클러스터링, 검색, 문장 유사도 등)에서 모델이 얻은 점수들의 평균을 기반으로 산정된다. 즉, 여러 벤치마크 데이터셋에서 모델의 성능을 측정하고, 이를 종합하여 평균 점수를 계산한 뒤, 이 평균 점수가 높은 순서대로 모델이 정렬된다.

**주요 평가 방식**

- **평가 태스크 종류**
  - 분류(Classification): F1 점수
  - 클러스터링(Clustering): V-measure
  - 쌍 분류(Pair Classification): Average Precision
  - 재정렬(Reranking): MRR@k, MAP
  - 검색(Retrieval): nDCG@k
  - 의미 유사도(STS): Spearman correlation
  - 요약(Summarization): Spearman correlation  
  각 태스크별로 대표적인 평가 지표가 다르며, 모델은 여러 태스크에서 평가를 받는다[2].

- **평균 점수 산정**
  - 각 태스크별로 모델이 얻은 점수를 모두 합산한 뒤, 태스크 수로 나누어 평균 점수를 구한다.
  - 이 평균 점수가 리더보드의 기본 순위 기준이 된다.

- **부분 평가 가능**
  - 모든 태스크를 수행하지 않아도 특정 태스크만 평가받아 부분 리더보드에 오를 수 있다. 예를 들어, 클러스터링 태스크만 평가받아 해당 부분 순위에 표시될 수 있다.

In [2]:
from openai import OpenAI
from dotenv import load_dotenv
import os

load_dotenv()  # .env파일 읽어 환경변수 등록
client = OpenAI()  # Openai api 응답 객체

In [3]:
response = client.embeddings.create(
    model='text-embedding-3-small',
    input=["Hello World!", "안녕하세요?"]
)

response

CreateEmbeddingResponse(data=[Embedding(embedding=[-0.0030193328857421875, -0.0567626953125, 0.02947998046875, 0.042999267578125, -0.04083251953125, -0.025177001953125, -0.01282501220703125, 0.03515625, -0.03155517578125, -0.01108551025390625, -0.0158843994140625, -0.031097412109375, -0.020294189453125, -0.024688720703125, 0.029632568359375, 0.035888671875, -0.038177490234375, 0.017822265625, 0.01137542724609375, 0.040771484375, 0.04754638671875, 0.0025005340576171875, -0.006389617919921875, -0.01392364501953125, 0.03485107421875, -0.01221466064453125, -0.04437255859375, 0.0185089111328125, 0.0237274169921875, -0.0433349609375, 0.044952392578125, -0.036224365234375, -0.010223388671875, 0.005977630615234375, 0.00621795654296875, 0.0006060600280761719, -0.001708984375, 0.00647735595703125, -0.0014619827270507812, -0.02398681640625, 0.0121612548828125, -0.0277862548828125, 0.01025390625, 0.040313720703125, -0.05206298828125, 0.0291748046875, -0.05596923828125, 0.01230621337890625, 0.03167724609375, 0.042633056640625, -0.0216522216796875, 0.0102691650390625, 0.0171966552734375, 0.0811767578125, -0.037109375, -0.04937744140625, 0.016632080078125, 0.06744384765625, -0.045684814453125, 0.006938934326171875, 0.0105438232421875, 0.0086212158203125, -0.008026123046875, 0.012054443359375, 0.032928466796875, -0.0161590576171875, -0.0207061767578125, -0.002410888671875, -0.01194000244140625, 0.06280517578125, 0.0121917724609375, 0.03961181640625, 0.0020599365234375, -0.00559234619140625, -0.050689697265625, -0.0147705078125, -0.0278472900390625, -0.0109405517578125, -0.0218048095703125, -0.06610107421875, -0.0439453125, 0.0364990234375, -0.05096435546875, -0.04888916015625, -0.01178741455078125, 0.001026153564453125, -0.0280914306640625, -0.0157318115234375, -0.027374267578125, -0.00039386749267578125, -0.00763702392578125, 0.00850677490234375, -0.037628173828125, 0.0085906982421875, 0.009368896484375, -0.0137939453125, -0.0100555419921875, 0.05267333984375, 0.06591796875, -0.04248046875, 0.0180511474609375, -0.040679931640625, 0.0369873046875, -0.023193359375, 0.0237579345703125, -0.0010156631469726562, -0.01177978515625, -0.031463623046875, -0.03875732421875, 0.012298583984375, -0.13525390625, -0.036285400390625, 0.0169525146484375, 0.0027923583984375, -0.0020427703857421875, 0.009979248046875, 0.05352783203125, -0.036224365234375, 0.0258026123046875, -0.0543212890625, 0.00821685791015625, -0.016876220703125, -0.01470184326171875, -0.050506591796875, -0.036346435546875, -0.023223876953125, -0.0229644775390625, 0.04913330078125, -0.03936767578125, 0.0036029815673828125, 0.050018310546875, 0.0263214111328125, 0.00988006591796875, -0.041015625, -0.03271484375, -0.00292205810546875, -0.03228759765625, -0.01117706298828125, -0.0408935546875, 0.046356201171875, 0.05157470703125, -0.01953125, -0.001003265380859375, -0.0203704833984375, -0.0164794921875, -0.032958984375, -0.01273345947265625, 0.0216064453125, -0.01303863525390625, -0.0116119384765625, 0.042938232421875, 0.042755126953125, -0.036468505859375, 0.01068115234375, 0.02301025390625, -0.0278167724609375, 0.035797119140625, -0.031829833984375, -0.0132904052734375, 0.0304718017578125, 0.0509033203125, 0.0304107666015625, -0.034820556640625, 0.005283355712890625, 0.006572723388671875, 0.006015777587890625, 0.012176513671875, -0.017120361328125, -0.04736328125, -0.0105438232421875, 0.03460693359375, 0.01140594482421875, -0.0265045166015625, -0.049957275390625, -0.00926971435546875, 0.015594482421875, 0.00353240966796875, -0.06219482421875, 0.00421905517578125, -0.02752685546875, 0.037261962890625, 0.057373046875, 0.009765625, -0.007587432861328125, -0.037200927734375, -0.0170135498046875, -0.024017333984375, 0.0001811981201171875, -0.01251220703125, -0.0244598388671875, -0.052001953125, 0.051666259765625, 0.036407470703125, -0.005222320556640625, 0.003948211669921875, -0.038787841796875, 0.06646728515625, 0.0023899078369140625, -0.005786895751953125, 0.0250701904296875, 0.004688262939453125, 0.0167694091796875, -0.034820556640625, -0.04449462890625, -0.0176239013671875, -0.038421630859375, -0.0008378028869628906, 0.0670166015625, -0.00939178466796875, -0.03515625, 0.07513427734375, -0.006839752197265625, -0.0290679931640625, -0.0081939697265625, -0.04388427734375, 0.000988006591796875, 0.0364990234375, 0.0226593017578125, 0.00049591064453125, -0.044708251953125, -0.04522705078125, 0.05877685546875, 0.07098388671875, -0.006008148193359375, 0.037841796875, -0.0054168701171875, 0.002254486083984375, -0.03387451171875, 0.058807373046875, 0.01393890380859375, 0.022979736328125, 0.01910400390625, 0.021148681640625, -0.03863525390625, -0.0019435882568359375, -0.0258941650390625, 0.03955078125, -0.00804901123046875, 0.0033893585205078125, 0.00902557373046875, -0.04913330078125, -0.004302978515625, -0.0002053976058959961, 0.043426513671875, 0.040924072265625, -0.0126953125, -0.0325927734375, -0.0213165283203125, 0.0229644775390625, 0.032501220703125, 0.037445068359375, 0.0111083984375, -0.00708770751953125, -0.005184173583984375, 0.0278167724609375, 0.0017061233520507812, -0.008880615234375, -0.0037784576416015625, 0.034576416015625, -0.0202484130859375, -0.0455322265625, -0.0421142578125, -0.023040771484375, -0.03436279296875, 0.0006933212280273438, -0.0293121337890625, 0.002422332763671875, -0.0081939697265625, -0.04541015625, -0.01517486572265625, 0.038299560546875, 0.01477813720703125, 0.06103515625, -0.01904296875, -0.007190704345703125, -0.00661468505859375, -0.0092315673828125, 0.0019025802612304688, -0.0153656005859375, 0.03863525390625, -0.0264739990234375, -0.00508880615234375, 0.016387939453125, 0.047332763671875, -0.0428466796875, -0.0040740966796875, 0.0136260986328125, -0.0005693435668945312, -0.019561767578125, -0.01465606689453125, 0.039215087890625, 0.054840087890625, 0.03424072265625, -0.0182952880859375, 0.0212860107421875, 0.01325225830078125, 0.0115966796875, -0.03363037109375, 0.04559326171875, -0.0170745849609375, 0.062103271484375, -0.0107879638671875, 0.0308685302734375, 0.0218963623046875, 0.004489898681640625, 0.032135009765625, 0.0259857177734375, -0.035308837890625, 0.056549072265625, -0.007564544677734375, -0.00310516357421875, -0.0165557861328125, 0.06317138671875, -0.02423095703125, -0.0236053466796875, -0.06756591796875, -0.0191497802734375, -0.024810791015625, 0.0157470703125, -0.034576416015625, 0.035186767578125, -0.05938720703125, -0.01451873779296875, -0.01451873779296875, 0.01100921630859375, -0.0248870849609375, 0.0614013671875, 0.0184326171875, 0.014312744140625, -0.00952911376953125, 0.0032558441162109375, -0.0133209228515625, -0.01012420654296875, -0.00921630859375, 0.0021190643310546875, -0.012115478515625, -0.03131103515625, 0.034210205078125, 0.0162811279296875, 0.0362548828125, -0.0127105712890625, -0.033905029296875, 0.0088653564453125, -0.0231475830078125, 0.006328582763671875, -0.00496673583984375, 0.043426513671875, -0.022308349609375, -0.0055694580078125, -0.0004050731658935547, -0.0021190643310546875, -0.0120849609375, -0.0067138671875, -0.0163116455078125, -0.01580810546875, -0.00896453857421875, 0.060638427734375, -0.0217742919921875, 0.003742218017578125, 0.03826904296875, -0.002197265625, -0.021148681640625, -0.006683349609375, 0.00396728515625, 0.034393310546875, 0.0283203125, -0.006969451904296875, -0.04779052734375, -0.007701873779296875, 0.0286712646484375, 0.00904083251953125, -0.0045623779296875, 0.00820159912109375, -0.013275146484375, -0.0302581787109375, -0.033843994140625, 0.0247650146484375, -0.0096282958984375, 0.042633056640625, -0.0005059242248535156, 0.017242431640625, 0.01486968994140625, -0.0056610107421875, -0.024017333984375, 0.0023746490478515625, -0.01354217529296875, 0.0259246826171875, 0.00946044921875, 0.01322174072265625, -0.01482391357421875, 0.012237548828125, -0.01363372802734375, 0.001010894775390625, 0.00688934326171875, 0.002239227294921875, -0.026580810546875, 0.004520416259765625, 0.00238037109375, -0.0164031982421875, -0.059417724609375, 0.064453125, -0.0263824462890625, 0.0133056640625, 0.005126953125, -0.047882080078125, -0.0601806640625, -0.00830078125, 0.06414794921875, -0.016571044921875, -0.034454345703125, -0.002307891845703125, -0.055633544921875, 0.036376953125, 0.0226287841796875, -0.020782470703125, -0.0019702911376953125, -0.0280609130859375, -0.04876708984375, 0.02362060546875, 0.0043182373046875, 0.006320953369140625, 0.021240234375, -0.049591064453125, 0.025970458984375, -0.0113067626953125, 0.04864501953125, 0.042022705078125, -0.016937255859375, -0.01406097412109375, -0.0821533203125, -0.00441741943359375, -0.0167388916015625, -0.0096435546875, 0.02593994140625, -0.00624847412109375, -0.04345703125, 0.0120086669921875, -0.007904052734375, 0.03338623046875, 0.03143310546875, -0.0032596588134765625, -0.0024433135986328125, 0.0150299072265625, 0.0104827880859375, -0.0005908012390136719, -0.037750244140625, -0.005218505859375, -0.025054931640625, -0.0124969482421875, 0.006107330322265625, 0.00994873046875, -0.06622314453125, 0.02783203125, 0.01201629638671875, -0.00197601318359375, -0.005023956298828125, 0.02301025390625, 0.0203704833984375, 0.0015401840209960938, 0.013458251953125, 0.0172882080078125, 0.00858306884765625, -0.06817626953125, 0.03326416015625, 0.033843994140625, -0.00913238525390625, -0.0193939208984375, 0.011688232421875, -0.0269775390625, -0.048126220703125, -0.015869140625, 0.0117950439453125, 0.0296630859375, -0.032501220703125, -0.0014677047729492188, -0.0173797607421875, -0.028167724609375, 0.01218414306640625, -0.036407470703125, -0.0063323974609375, 0.060302734375, 0.0106658935546875, 0.023406982421875, 0.0203399658203125, 0.007129669189453125, 0.0574951171875, -0.07666015625, -0.00777435302734375, -0.035003662109375, -0.0176849365234375, -0.0631103515625, 0.04766845703125, 0.05059814453125, -0.017730712890625, -0.0155487060546875, -0.031463623046875, 0.0186309814453125, -0.0125732421875, -0.007080078125, -0.01467132568359375, 0.0169830322265625, -0.02587890625, -0.00403594970703125, 0.03448486328125, 0.07293701171875, -0.0090179443359375, -0.045684814453125, -0.0229339599609375, 0.0176544189453125, -0.043121337890625, -0.061798095703125, 2.658367156982422e-05, 0.00820159912109375, -0.0287933349609375, -0.0004038810729980469, -0.005367279052734375, -0.00472259521484375, 0.0182952880859375, -0.0075225830078125, -0.0193023681640625, 0.01087188720703125, 0.030029296875, -0.00789642333984375, -0.028350830078125, 0.023895263671875, 0.006805419921875, -0.03265380859375, 0.00260162353515625, -0.0240631103515625, 0.0208587646484375, 0.0177154541015625, -0.015655517578125, 0.039459228515625, 0.0164642333984375, -0.0223846435546875, -0.00589752197265625, -0.0125274658203125, 0.0161285400390625, -0.01265716552734375, 0.00305938720703125, 0.01204681396484375, 0.0164947509765625, 0.00994873046875, 0.01324462890625, -0.015106201171875, 0.0020771026611328125, 0.0246124267578125, 0.0179901123046875, 0.00983428955078125, 0.02490234375, -0.0006427764892578125, -0.010101318359375, -0.0174713134765625, -0.0163116455078125, 0.0279998779296875, -4.756450653076172e-05, -0.0162353515625, -0.00846099853515625, 0.0092620849609375, 0.062042236328125, 0.01381683349609375, -0.00769805908203125, 0.023345947265625, 0.034515380859375, -0.0128326416015625, 0.01061248779296875, 0.00383758544921875, -0.028289794921875, -0.046478271484375, -0.039642333984375, -0.02935791015625, -0.024322509765625, -0.006473541259765625, -0.06292724609375, 0.0218353271484375, 0.0027332305908203125, 0.01335906982421875, 0.0009284019470214844, 0.0224609375, -0.0181121826171875, -0.0165863037109375, -0.00720977783203125, -0.0081787109375, 0.03277587890625, -0.0496826171875, 0.038818359375, 0.0163116455078125, 0.00870513916015625, 0.022735595703125, -0.035552978515625, 0.0194091796875, 0.0269927978515625, 0.0196990966796875, 0.04705810546875, -0.010101318359375, -0.01187896728515625, -0.00986480712890625, 0.01255035400390625, -0.028961181640625, 0.049285888671875, 0.0304412841796875, 0.01078033447265625, -0.01016998291015625, -0.0310821533203125, 0.010162353515625, 0.0017595291137695312, -0.0220947265625, -0.00751495361328125, -0.0009975433349609375, -0.059478759765625, -0.03424072265625, 0.04071044921875, -0.0121612548828125, -0.0535888671875, -0.02398681640625, 0.039459228515625, -0.023468017578125, 0.00951385498046875, 0.01184844970703125, -0.036041259765625, -0.0040435791015625, -0.039215087890625, -0.0017232894897460938, 0.030029296875, 0.00131988525390625, 0.02703857421875, -0.029449462890625, -0.01049041748046875, -0.018829345703125, 0.00011616945266723633, 0.0270233154296875, 0.00649261474609375, 0.03582763671875, -0.01015472412109375, -0.0091552734375, 0.00011718273162841797, 0.013885498046875, 0.00366973876953125, -0.0081939697265625, -0.0221710205078125, 0.030609130859375, -0.006931304931640625, 0.01270294189453125, -0.0197601318359375, 0.058868408203125, 0.020751953125, 0.0179290771484375, 0.032135009765625, 0.00690460205078125, -0.01015472412109375, 0.036163330078125, 0.0176849365234375, 0.0194091796875, 0.0130462646484375, 0.0210113525390625, -0.0201416015625, -0.036712646484375, -0.01617431640625, -0.03289794921875, 0.02801513671875, -0.015777587890625, 0.05218505859375, -0.035491943359375, -0.0113983154296875, -0.01142120361328125, 0.01000213623046875, -0.0186920166015625, 0.018585205078125, 0.0019273757934570312, -0.0199127197265625, -0.0167236328125, -0.002292633056640625, 0.050140380859375, -0.0118255615234375, 0.02734375, -0.006343841552734375, -0.0143585205078125, -0.005779266357421875, 0.008270263671875, -0.013519287109375, 0.0198211669921875, 0.01806640625, -0.0384521484375, -0.0100250244140625, 0.005809783935546875, 0.0236053466796875, 0.0141143798828125, 0.0219879150390625, -0.007579803466796875, 0.007183074951171875, -0.0271148681640625, -0.0322265625, 0.01078033447265625, 0.015594482421875, 0.0006451606750488281, -0.0310821533203125, 0.0258941650390625, -0.004161834716796875, -0.005123138427734375, -0.06292724609375, 0.0289306640625, -0.013031005859375, -0.021697998046875, 0.017608642578125, 0.008636474609375, -0.00726318359375, -0.033477783203125, 0.0222625732421875, 0.040374755859375, 0.01800537109375, -0.040008544921875, -0.0084991455078125, -0.028350830078125, -0.002704620361328125, -0.046295166015625, -0.01183319091796875, -0.03179931640625, -0.036834716796875, -0.0018520355224609375, -0.01059722900390625, -0.0340576171875, 0.005466461181640625, -0.02008056640625, 0.007556915283203125, -0.0164794921875, -0.016845703125, 0.01427459716796875, -0.00887298583984375, 0.030059814453125, 0.00737762451171875, 0.006061553955078125, -0.003116607666015625, 0.003566741943359375, -2.8252601623535156e-05, 0.00313568115234375, -0.003932952880859375, -0.043609619140625, -0.01261138916015625, 0.0185394287109375, -0.0389404296875, -0.0350341796875, 0.01296234130859375, 0.0296478271484375, 0.011871337890625, -0.0272216796875, -0.01276397705078125, 0.019287109375, 0.00994873046875, -0.005832672119140625, -0.00937652587890625, -0.004901885986328125, 0.01267242431640625, -0.0289459228515625, 0.0026721954345703125, 0.01074981689453125, -0.005157470703125, 0.036041259765625, 0.0225830078125, -0.01496124267578125, 0.02099609375, -0.01390838623046875, 0.0408935546875, 0.00406646728515625, 0.04095458984375, -0.006282806396484375, 0.0086822509765625, 0.00909423828125, 0.0115966796875, -0.007129669189453125, 0.00492095947265625, 0.0303497314453125, 0.0118255615234375, 0.019775390625, 0.01032257080078125, 0.0005984306335449219, 0.007354736328125, -0.0298004150390625, 0.01119232177734375, -0.04095458984375, -0.0279693603515625, -0.004100799560546875, -0.00045037269592285156, -0.01390838623046875, -0.0093536376953125, 0.01261138916015625, -0.005397796630859375, 0.0163116455078125, -0.01290130615234375, 0.0136871337890625, -0.04150390625, -0.045562744140625, -0.022491455078125, -0.0020923614501953125, -0.016387939453125, 0.024261474609375, 0.058990478515625, -0.0014019012451171875, -0.0081024169921875, 0.019500732421875, -0.00608062744140625, -0.0079803466796875, -0.04595947265625, 0.02685546875, 0.02850341796875, -0.0022430419921875, 0.002574920654296875, -0.0243377685546875, 0.005352020263671875, -0.002864837646484375, -0.0027332305908203125, 0.0123291015625, 0.040679931640625, -0.006488800048828125, 0.0023651123046875, 0.019500732421875, -0.019317626953125, 0.0158538818359375, -0.016357421875, 0.024322509765625, 0.0071563720703125, 0.015380859375, 0.0063934326171875, -0.03173828125, -0.00794219970703125, 0.0706787109375, 0.0255584716796875, -0.00751495361328125, 0.031158447265625, 0.046875, -0.015716552734375, -0.0096588134765625, -0.0079345703125, -0.0178680419921875, -0.018524169921875, 0.0006384849548339844, 0.023956298828125, 0.01678466796875, -0.0235443115234375, -0.00885009765625, -0.00921630859375, -0.0175933837890625, -0.01580810546875, -0.0157623291015625, -0.01233673095703125, 0.04925537109375, -0.024871826171875, 0.0095977783203125, -0.0012540817260742188, -0.00817108154296875, 0.0018711090087890625, -0.027435302734375, -0.04229736328125, 0.01403045654296875, -0.01490020751953125, -0.0245819091796875, 0.01812744140625, -0.005695343017578125, -0.01486968994140625, -0.0150146484375, -0.0284881591796875, -0.006862640380859375, 0.02935791015625, 0.0157318115234375, 0.0256805419921875, 0.0265655517578125, -0.00281524658203125, 0.015106201171875, 0.00717926025390625, 0.049957275390625, 0.047119140625, -0.0046234130859375, 0.0157623291015625, -0.0062103271484375, -0.00455474853515625, 0.01213836669921875, 0.03656005859375, -0.061279296875, 0.031280517578125, 0.0015497207641601562, -0.0247650146484375, 0.02874755859375, 0.0275421142578125, -0.005352020263671875, -0.01517486572265625, -0.01953125, -0.0382080078125, 0.007274627685546875, 0.01139068603515625, 0.0265655517578125, -0.01085662841796875, -0.009002685546875, 0.01019287109375, -0.00528717041015625, -0.0118408203125, -0.007266998291015625, -0.019989013671875, -0.00614166259765625, 0.044219970703125, 0.0118865966796875, 0.0025959014892578125, 0.0032939910888671875, -0.01947021484375, 0.0084686279296875, 0.034027099609375, 0.01354217529296875, -0.00022363662719726562, -0.00504302978515625, -0.00911712646484375, 0.003917694091796875, -0.0040130615234375, -0.00030803680419921875, -0.05279541015625, 0.0220947265625, 0.017242431640625, 0.0550537109375, 0.029632568359375, 0.0012264251708984375, 0.0207061767578125, 0.0028972625732421875, 0.02197265625, -0.005828857421875, -0.056182861328125, -0.03192138671875, 0.02252197265625, -0.0223236083984375, 0.009429931640625, -0.0418701171875, 0.0640869140625, 0.0201416015625, -0.01245880126953125, 0.01666259765625, 0.0068817138671875, -0.0283203125, 0.0214385986328125, 0.008697509765625, 0.0002911090850830078, -0.036529541015625, 0.02294921875, -0.0088348388671875, -0.0399169921875, -0.02520751953125, 0.0239105224609375, 0.016143798828125, -0.0014047622680664062, 0.05419921875, 0.02069091796875, 0.01076507568359375, 0.00019299983978271484, -0.007049560546875, -0.00939178466796875, -0.0213775634765625, -0.01092529296875, -0.005695343017578125, 0.0018911361694335938, -0.022125244140625, 0.024688720703125, 0.051605224609375, -0.006107330322265625, -0.01525115966796875, 0.0052032470703125, -0.0248565673828125, -0.02325439453125, -0.0236968994140625, -0.00739288330078125, 0.004367828369140625, 0.0003020763397216797, -0.0283660888671875, -0.0089874267578125, 0.014373779296875, -0.01255035400390625, -0.012908935546875, 0.006900787353515625, 0.0238494873046875, 0.0210418701171875, -0.0005211830139160156, -0.01325225830078125, -0.026153564453125, 0.027374267578125, 0.03924560546875, 0.0009446144104003906, 0.021331787109375, -0.019439697265625, 0.0107879638671875, 0.00251007080078125, -0.022308349609375, 0.00994873046875, 0.0187225341796875, 0.007747650146484375, -0.0246124267578125, -0.014678955078125, 0.0146636962890625, 0.0021877288818359375, -0.050262451171875, 0.023040771484375, 0.044830322265625, -0.01007080078125, -0.01785

In [ ]:
len(response.data[0].embedding)  # 첫 번째 문장의 임베딩 벡터 길이

1536

In [ ]:
emb_vec0 = response.data[0].embedding  # 첫 번째 문장의 임베딩 벡터
emb_vec1 = response.data[1].embedding

print(len(emb_vec0))  # 첫 번째 문장의 임베딩 벡터 길이
print(len(emb_vec1))

1536
1536

In [7]:
def text_to_embedding(texts, model='text-embedding-3-small'):
    texts = [text.replace("\n", ' ') for text in texts]
    response = client.embeddings.create(model=model, input=texts)

    return [data.embedding for data in response.data]

vecs = text_to_embedding(["Hello World!", "안녕하세요?"])

print(len(vecs[0]))
print(len(vecs[1]))

1536
1536

### 음식리뷰 임베딩 처리

https://www.kaggle.com/datasets/snap/amazon-fine-food-reviews   

corpus를 임베딩 벡터로 변환하고, 이후에는 이 임베딩 벡터로 VectorDB에 저장해 놓고, 유사도를 통한 검색이 가능하다.

In [9]:
import pandas as pd

review_df = pd.read_csv('fine_food_reviews_1k.csv', index_col=0)
print(review_df.info())
review_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Time       1000 non-null   int64
 1   ProductId  1000 non-null   str
 2   UserId     1000 non-null   str
 3   Score      1000 non-null   int64
 4   Summary    1000 non-null   str
 5   Text       1000 non-null   str
dtypes: int64(2), str(4)
memory usage: 450.7 KB
None

,Time,ProductId,UserId,Score,Summary,Text
0,1351123200,B003XPF9BO,A3R7JR3FMEBXQB,5,where does one start...and stop... with a tre...,Wanted to save some to bring to my Chicago fam...
1,1351123200,B003JK537S,A3JBPC3WFUT5ZP,1,Arrived in pieces,"Not pleased at all. When I opened the box, mos..."
2,1351123200,B000JMBE7M,AQX1N6A51QOKG,4,"It isn't blanc mange, but isn't bad . . .",I'm not sure that custard is really custard wi...
3,1351123200,B004AHGBX4,A2UY46X0OSNVUQ,3,These also have SALT and it's not sea salt.,I like the fact that you can see what you're g...
4,1351123200,B001BORBHO,A1AFOYZ9HSM2CZ,5,Happy with the product,My dog was suffering with itchy skin. He had ...

In [10]:
review_df = review_df[['Summary', 'Text']]

review_df['Content'] = 'Title: ' + review_df['Summary'].str.strip() + '; Content: ' + review_df['Text'].str.strip()
review_df

,Summary,Text,Content
0,where does one start...and stop... with a tre...,Wanted to save some to bring to my Chicago fam...,Title: where does one start...and stop... wit...
1,Arrived in pieces,"Not pleased at all. When I opened the box, mos...",Title: Arrived in pieces; Content: Not pleased...
2,"It isn't blanc mange, but isn't bad . . .",I'm not sure that custard is really custard wi...,"Title: It isn't blanc mange, but isn't bad . ...."
3,These also have SALT and it's not sea salt.,I like the fact that you can see what you're g...,Title: These also have SALT and it's not sea s...
4,Happy with the product,My dog was suffering with itchy skin. He had ...,Title: Happy with the product; Content: My dog...
...,...,...,...
995,Delicious!,I have ordered these raisins multiple times. ...,Title: Delicious!; Content: I have ordered the...
996,Good Training Treat,My dog will come in from outside when I am tra...,Title: Good Training Treat; Content: My dog wi...
997,Jamica Me Crazy Coffee,Wolfgang Puck's Jamaica Me Crazy is that wonde...,Title: Jamica Me Crazy Coffee; Content: Wolfga...
998,Party Peanuts,Great product for the price. Mix with the Asia...,Title: Party Peanuts; Content: Great product f...
999,I love Maui Coffee!,My first experience with Maui Coffee was bring...,Title: I love Maui Coffee!; Content: My first ...

In [11]:
# Content를 리스트로 변환 후 임베딩 생성 -> embedding 컬럼 저장
review_df['embedding'] = text_to_embedding(review_df['Content'].tolist())
review_df.head()

,Summary,Text,Content,embedding
0,where does one start...and stop... with a tre...,Wanted to save some to bring to my Chicago fam...,Title: where does one start...and stop... wit...,"[0.036651611328125, -0.023193359375, -0.030471..."
1,Arrived in pieces,"Not pleased at all. When I opened the box, mos...",Title: Arrived in pieces; Content: Not pleased...,"[0.01140594482421875, 0.0343017578125, -0.0411..."
2,"It isn't blanc mange, but isn't bad . . .",I'm not sure that custard is really custard wi...,"Title: It isn't blanc mange, but isn't bad . ....","[0.0032253265380859375, 0.01265716552734375, -..."
3,These also have SALT and it's not sea salt.,I like the fact that you can see what you're g...,Title: These also have SALT and it's not sea s...,"[-0.0028896331787109375, 0.01462554931640625, ..."
4,Happy with the product,My dog was suffering with itchy skin. He had ...,Title: Happy with the product; Content: My dog...,"[0.01204681396484375, -0.0560302734375, 0.0167..."

In [ ]:
embed_df = review_df['embedding'].to_frame('embedding')  # Series(embedding) -> DataFrame 변환
embed_df.index = review_df['Content']  # 인덱스는 Content 텍스트
embed_df

                                                                                            embedding
Content
Title: where does one  start...and stop... with...  [0.036651611328125, -0.023193359375, -0.030471...
Title: Arrived in pieces; Content: Not pleased ...  [0.01140594482421875, 0.0343017578125, -0.0411...
Title: It isn't blanc mange, but isn't bad . . ...  [0.0032253265380859375, 0.01265716552734375, -...
Title: These also have SALT and it's not sea sa...  [-0.0028896331787109375, 0.01462554931640625, ...
Title: Happy with the product; Content: My dog ...  [0.01204681396484375, -0.0560302734375, 0.0167...
...                                                                                               ...
Title: Delicious!; Content: I have ordered thes...  [0.016448974609375, -0.039154052734375, -0.026...
Title: Good Training Treat; Content: My dog wil...  [-0.023040771484375, -0.0139007568359375, 0.00...
Title: Jamica Me Crazy Coffee; Content: Wolfgan...  [-0.02960205078125, -0.045745849609375, -0.026...
Title: Party Peanuts; Content: Great product fo...  [0.0010776519775390625, -0.0225830078125, -0.0...
Title: I love Maui Coffee!; Content: My first e...  [0.0191802978515625, -0.019317626953125, -0.03...

[1000 rows x 1 columns]

In [ ]:
# 유사도 검색 (Vector Search 기반 검색)
from sklearn.metrics.pairwise import cosine_similarity

# 쿼리와 가장 유사한 리뷰를 벡터 유사도로 Top-n개 검색하는 함수
def review_vector_search(query, embed_df=embed_df, top_n=5):
    query_emb = text_to_embedding([query])  # 사용자 쿼리를 임베딩 벡터로 변환

    df = embed_df.copy()
    df['cos_sim'] = df['embedding'].apply(lambda emb: cosine_similarity([emb], query_emb)[0, 0])

    df = df.sort_values('cos_sim', ascending=False).head(top_n)  # 유사도 높은 순 상위 n개
    df = df.reset_index()  # 인덱스 : Content -> 0부터 재생성 (Content는 컬럼으로 변환)
    df = df[['Content', 'cos_sim']]

    return df

pd.set_option('display.max_colwidth', None)  # Content가 잘리는 것 방지 (최대 출력 길이 제한 해제)
review_vector_search('delicious fruit')

,Content,cos_sim
0,"Title: Delicious!; Content: For anyone who says ""I don't like fruitcake"" or anyone who's never had fruitcake and wonders what all the fuss is about, try this. (As long as you're not allergic to tree nuts or any other ingredient.) It's chock-a-block with nuts and moist fruit. I will definitely be buying more.",0.649525
1,"Title: Delicious .; Content: These plums are sweet and juicy, and the aroma is like perfume. And it doesn't hurt that they are good for you, too.",0.612282
2,"Title: Delicious!; Content: Wonderful! Deep, rich, pure black raspberry syrup! Absolutely delicious on waffles, cheesecake, ice cream, yogurt, drinks, etc. Thrilled to see that there are at least some berry syrup makers who do not feel the need to ""sour"" the flavor of perfect berry products with citric acid!",0.599868
3,"Title: These are Delicious!; Content: Great taste, right price, fabulous snack! It is the only fruit I can get my little one to eat and I can't keep my high school son out of them either. They are great pick-me-ups on the way to my daughter's soccer practice or before my early morning run. And best of all, Amazon ships these right to my door every month. No more finding the right store who carries them. I just set up the automatic recurring shipment once and it works like a charm!",0.591969
4,Title: Delicious!; Content: I have ordered these raisins multiple times. They are always great and arrive timely. I can't go back to store bought chocolate covered raisins now! Love this product.,0.502419

cosine_similarity([emb], query_emb)
[emb] = [[0.123123123, ... , (1536개)]] => (1, 1536)
query_emb = (1, 1536)
코사인 유사도 계산시 [[0.649542]] => (1, 1) => [0, 0]은 값만 빼옴

In [15]:
review_vector_search('Best coffee')

,Content,cos_sim
0,"Title: Best coffee ever!; Content: In my opinion this is the best coffee ever! I've been drinking coffee for 50 plus years and this is what I serve to myself and friends. However, I wish I could find this grind in a pound size, so I could make a full pot rather than just a single cup.",0.622141
1,"Title: Great Coffee; Content: I have a coffee maker that grinds my coffee beans. It's hard to find whole bean decafinated coffee. When I find it in the brand that I like, I am excited. Seattle's Best is my favorite.",0.619311
2,Title: Good coffee.; Content: This is the best Donut Shop Blend out there. Though most k-cups taste a little freeze dried. Keurig needs to work on that. I prefer San Francisco Bay Coffee Company.,0.615143
3,"Title: Better than you-know-who's coffee...; Content: So my wife is a latte freak, and nursing, so decaf is the approved type. After the Senseo left the market, I struggled and found the <a href=""http://www.amazon.com/gp/product/B0047BIWSK"">Aerobie AeroPress Coffee and Espresso Maker</a> which is like a French Press for the 21st century. After getting our recipe figured out, my wife, who's been buying Venti Decaf Latte's at $4 a pop almost daily for years now declares that Seattle's best Level 3 Decaf in her home-made Latte is the best coffee she can get. We've tried other bands, and this is her favorite, hands down!",0.613122
4,"Title: BEST cup of coffee I've ever had!; Content: I thought I'd splurge and try this coffee. It costs much more than other decaf K-Cup options. But I hoped that meant it was better coffee. It IS better coffee. I've never had a better cup of coffee than this. It is excellent when compared to any other decaf or regular coffee I've tried.<br /><br />If you like BOLD, FLAVORFUL decaf coffee try this coffee and you'll really like it.",0.611989